### ISSUE TITLE
カスタム絵文字にライセンス(著作者)情報を付与できるように

### ISSUE THREAD

**Issue by yulog** [syuilo/Misskey#10091]
カスタム絵文字にメタ情報として、ライセンス(著作者)情報を含めるようにするのはどうでしょうか？

少し前にmisskey.ioでカスタム絵文字のライセンスに問題がないかといった話題がありました。
ライセンス情報を付与して、絵文字一覧ページで見られるようにすれば一定の意味はありそうです。

**Comment by KawaneRio** [comment]
これちょうどほしかった。

ただ<ruby>名称<rp>《</rp><rt>めいしょう</rt><rp>》</rp></ruby>は「その他」の<ruby>方<rp>《</rp><rt>はう</rt><rp>》</rp></ruby>が<ruby>好<rp>《</rp><rt>こ</rt><rp>》</rp></ruby>のましいと<ruby>我<rp>《</rp><rt>われ</rt><rp>》</rp></ruby>は<ruby>考<rp>《</rp><rt>かんが</rt><rp>》</rp></ruby>へる。

<ruby>強<rp>《</rp><rt>し</rt><rp>》</rp></ruby>いていふなら、<ruby>別<rp>《</rp><rt>べつ</rt><rp>》</rp></ruby>の<ruby>鯖<rp>《</rp><rt>さば</rt><rp>》</rp></ruby>の<ruby>絵文字<rp>《</rp><rt>えもじ</rt><rp>》</rp></ruby>を<ruby>輸入<rp>《</rp><rt>インポート</rt><rp>》</rp></ruby>する<ruby>際<rp>《</rp><rt>さい</rt><rp>》</rp></ruby>、その<ruby>絵文字<rp>《</rp><rt>えもじ</rt><rp>》</rp></ruby>の<ruby>名称<rp>《</rp><rt>めいしょう</rt><rp>》</rp></ruby>だけでなく、カテゴリ・タグ・<ruby>及<rp>《</rp><rt>およ</rt><rp>》</rp></ruby>びライセンス<ruby>用<rp>《</rp><rt>よう</rt><rp>》</rp></ruby>の「その他」も<ruby>同時<rp>《</rp><rt>どうじ</rt><rp>》</rp></ruby>に<ruby>輸入<rp>《</rp><rt>ゆにゅう</rt><rp>》</rp></ruby>できれば、より<ruby>多<rp>《</rp><rt>おほ</rt><rp>》</rp></ruby>くの<ruby>方〻<rp>《</rp><rt>かたがた</rt><rp>》</rp></ruby>が<ruby>幸<rp>《</rp><rt>しあは</rt><rp>》</rp></ruby>せになれるのではと<ruby>我<rp>《</rp><rt>われ</rt><rp>》</rp></ruby>は<ruby>思<rp>《</rp><rt>おも</rt><rp>》</rp></ruby>ふたり。

## English

I was just thinking about this too. 

Although, I prefer the term `Other` over `License` so that the space can be utilized more efficiently by Server Admins.
Also, if this feature is going to be implemented, it would be very nice to have it in a way so that when a Server imports an emoji from another Server, their Tags, Category, and Other would also be imported.

**Comment by yulog** [comment]
「その他」項目を設けて、運用上、著作者やライセンスを入れるのと、専用の項目を持っているのでは意味合いが変わってくると思います。

**Comment by sorairolake** [comment]
オープンコンテントの二次創作物である場合は著作権に関する情報の提供は重要[^1]ですし、完全に自作の場合もこれが提供されていることが望ましいと思います。

提供すべき情報としては:

- そのカスタム絵文字に適用されているライセンス[^2]
- そのカスタム絵文字の出所[^3]
- そのカスタム絵文字の作者
- そのカスタム絵文字の作成日

があると思います[^4]。

[^1]: CCライセンスの条項の著作権表示 (BY) や、パブリックドメインである理由 (著作権の保護期間の満了など) など
[^2]: パブリックドメインの場合も含む
[^3]: 完全に自作の場合のこれの明示、二次創作物の場合の著作権表示と出所へのリンクか書誌情報
[^4]: [ウィキメディア・コモンズ](https://commons.wikimedia.org/wiki/Commons:Licensing/ja#%E3%83%A9%E3%82%A4%E3%82%BB%E3%83%B3%E3%82%B9%E6%83%85%E5%A0%B1)を参照

**Comment by naskya** [comment]
Issue はクローズされましたが、絵文字の管理権限を持たないユーザーがライセンスの欄に書かれた情報を確認する方法はあるのでしょうか（見落としていたらすみませんが、絵文字の管理画面以外からアクセスできないように見えます）。

**Comment by yulog** [comment]
https://github.com/misskey-dev/misskey/commit/ed51209172441927d24339f0759a5badbee3c9b6 で対応されたようです。
