### ISSUE TITLE
Unable to use post search function but user search function is normal

### ISSUE THREAD

**Issue by huaizhu1** [syuilo/Misskey#10399]
## 💡 Summary
Unable to use post search function but user search function is normal

## 🤬 Actual Behavior
The post search function shows that it is not working properly

## 📝 Steps to Reproduce

1.
2.
3.

## 📌 Environment
Debian11
The building method is docker
The built version is the latest version

Misskey version:
Your OS:
Your browser:

**Comment by CyberRex0** [comment]
Since 13.10.0, post search feature is disabled by default.
To re-enable, Go to Control Panel > Roles > Role Template > Usage of note search then click the toggle button and turn into enabled then save the settings.
<img width="456" alt="image" src="https://user-images.githubusercontent.com/26585194/227257810-06953567-5195-4574-804f-5cba74d12f50.png">

**Comment by huaizhu1** [comment]
thanks a lot ,problem solved

**Comment by genewitch** [comment]
Is there a reason this is disabled by default? Resource usage, bandwidth?
