### ISSUE TITLE
Scroll position isn't kept when navigating back

### ISSUE THREAD

**Issue by fireattack** [syuilo/Misskey#11068]
## 💡 Summary

When viewing TL, if you click any note detail or user, it will jump to that note/user's page. Now, if you click back, it goes back to TL.

I find this old issue #6033 which basically is the same thing, but it was supposed to be fixed long time ago.

## 🥰 Expected Behavior

The previous TL scroll position is kept.

## 🤬 Actual Behavior

It always resets back to the top.

## 📝 Steps to Reproduce

1. Open TL.
2. Scroll down.
3. Click detail or username for any note.

### 💻 Frontend
* Model and OS of the device(s): 
  Windows 10 generic desktop, and Android 13 on Pixel 7
* Browser:
   Chrome 114.0.5735.199 (Official Build) (64-bit) (cohort: Stable) 
* Server URL:
   https://misskey.io, https://live-theater.net/
* Misskey:
  13.13.2, 13.13.1

**Comment by jojobii-arks** [comment]
Would like to see this fixed!

**Comment by jojobii-arks** [comment]
Did some research into this. It seems like this logic exists in the router file in order to handle scroll persistence on the router "push" event.

https://github.com/misskey-dev/misskey/blob/644023316e85ed9d238007ef6b2177e25c98cf9a/packages/frontend/src/router.ts#L512-L547

However, as mentioned in the comment, the functionality does not work in "Deck" view, and similarly does not work in "Default" view; this is because the scroll is being handled in the timeline container, rather than in the window.

<img width="1800" alt="CleanShot 2023-07-07 at 22 11 20@2x" src="https://github.com/misskey-dev/misskey/assets/78003700/d60f848f-1bc8-4a9d-bc0b-8c7a063ddbf8">

This STILL works in Classic UI though, since the scrolling is happening in the window itself.

https://github.com/misskey-dev/misskey/assets/78003700/f9531e7e-4775-4ba2-94aa-fe628bd735df

Also, while I'm showing Classic UI, the scroll persistence logic gets messed up if the timeline moves too quickly when going back in the browser.

https://github.com/misskey-dev/misskey/assets/78003700/575ed0a4-97ee-4d14-98cf-bb7fade08b56

There's a lot of moving parts to this... 🥲
