### ISSUE TITLE
Profile only shows pinned notes and the "no notes" graphic since `2023.10.0`

### ISSUE THREAD

**Issue by Sakrecoer** [syuilo/Misskey#12120]
## 💡 Summary

Since upgrading to `2023.10.0` all profiles on my instance are empty bellow pinned note. The "no notes" graphic shows. I can still find the notes in the "notes" tab.

See: https://s.basspistol.org/@hq

## 🥰 Expected Behavior

Display the latest notes bellow pinned notes. Or let it be found under "notes" tab, but remove the "no notes" graphic

## 🤬 Actual Behavior

No notes shown bellow pinned notes section, and then the "no notes" graphic that makes it look like an error

### 💻 Frontend

* Server URL:  https://s.basspistol.org/@hq
* Misskey: 2023.10.2

### 🛰 Backend (for server admin)

* Installation Method or Hosting Service: Manual 
* Misskey: 2023.10.2
* Node: 18.17.1
* PostgreSQL: 12.16 (Ubuntu 12.16-0ubuntu0.20.04.1)
* Redis: 7.2.2
* OS and Architecture: Ubuntu 20.04.6 LTS

**Comment by Sakrecoer** [comment]
Seeing [this profile](https://s.basspistol.org/@herr_irrtum) I'm guessing the issue is that my notes are not cool enough (very few interactions) and therefor do not show up in "featured"? :D Can it be?

**Comment by Sakrecoer** [comment]
oh... strange that link (https://s.basspistol.org/@herr_irrtum) breaks the front end now somehow... It works when access from within the UI... Only happens with that profile it seems

**Comment by ryanho** [comment]
After 2023.10.0, changes were made to the trending system to improve system performance.

The quoted note mentions that the sampling method for featured posts will be improved. Instead of adding a point for each reaction or renote, a proportional sampling method will be used. For example, only 30% of the reaction or renote to the same post will be awarded points, and 70% of the reaction or renote will not take any action, thus reducing the burden on the system by 70%.

quoted note: https://misskey.io/notes/9khrov5akh

**Comment by Sakrecoer** [comment]
Thank you for clarifying this to me.

wouldn't it be better to hide the featured section all together if it is empty? As it looks now it seems like it is broken when empty.

**Comment by piko-piko** [comment]
Not displaying notes in the profile is just counterintuitive. I don't get the performance explanation - people who visit someone profile probably want to check what they're writing, so they're intending to click on the "notes" tab anyway. If there is any "performance improvement", it's because people who visit the profile are tricked, that there are no notes.

**Comment by zyoshoka** [comment]
Seems to be fixed in https://github.com/misskey-dev/misskey/commit/390602837bf85a01e0c2f91deb3bab6770a87f0d
