### ISSUE TITLE
[GoToSocial] Aproving request from GtS appears with some delay

### ISSUE THREAD

**Issue by SadmL** [syuilo/Misskey#14915]
### 💡 Summary

Approval request for locked Misskey or Sharkey (tested on them) account can be delivered after some time or only after several attempts, or not delivered at all, or mix of all 3 of this. Waiting time is up to 2 mins.
I don't think that happens due lack of stable connection, at least on my side, I have 300MiB bandwidth. I tested it on 2 separate servers, 1st Misskey account is mine, 2nd Sharkey is other person.

Video demos (proofs)

<details><summary>Phanpy</summary>
<p>

https://github.com/user-attachments/assets/a3bc4554-136e-4083-beda-619b5548670e

</p>
</details> 

<details><summary>Moshidon</summary>
<p>

https://github.com/user-attachments/assets/2afde2f5-c379-442a-96f3-2da8174f514d

</p>
</details> 

But I got this request off record a bit later.

Unfortunately, I can't provide any logs for Misskey, because I haven't any Misskey instance to admin.

Of course I asked GtS devs first about it here https://github.com/superseriousbusiness/gotosocial/issues/3523, but it's not on their side.

### 🥰 Expected Behavior

(almost) Instant notification of approval request to follow locked account

### 🤬 Actual Behavior

Notification of approval request appearing after some time or not appearing at all

### 📝 Steps to Reproduce

1. Find locked Misskey account
2. Try to request an approval to follow from any client with GoToSocial account

### 💻 Frontend Environment

* Model and OS of the device(s): PC, EndeavourOS Linux (Arch-based) 
* Browser: Librewolf 132.0-1
* Server URL: shitpost.poridge.club
* Misskey: 2024.10.1

### 🛰 Backend Environment (for server admin)

* Installation Method or Hosting Service:
* Misskey:
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by CDN18** [comment]
I encountered the same issue. The problem seems to be in this part of the code: https://github.com/misskey-dev/misskey/blob/develop/packages/backend/src/core/activitypub/models/ApPersonService.ts#L596. It looks like Misskey requires the target account to have a shared inbox here (which isn't yet implemented by GoToSocial), and if not, it gives the error: `UpdateValuesMissingError: Cannot perform update query because update values are not defined. Call "qb.set(...)" method to specify updated values.`

For more details, see: https://github.com/superseriousbusiness/gotosocial/issues/3523#issuecomment-2466436678

If that's the case, could Misskey consider falling back to using the inbox in this situation?
