### ISSUE TITLE
Issues with Federation tab in the Control Panel

### ISSUE THREAD

**Issue by EpicnessTwo** [syuilo/Misskey#7947]
## 💡 Summary

When selecting the first instance within the federation tab, it will bring up the information regarding that instance. However, clicking on any other instance after this will still bring up the information for the first instance that was clicked.

## 🙂 Expected Behavior

The correct information to be loaded for the instance that was clicked.

## ☹️ Actual Behavior

![](https://catgirlsfor.science/d2a8c634-6755-4a0a-9619-b321cfcddb59)

## 📝 Steps to Reproduce

1. Open the Control Panel
2. Navigate to the Federation tab
3. Click on any instance
4. Click the back button
5. Click on any other instance

## 📌 Environment

Windows 10, Google Chrome (observed this to happen on Firefox too)

**Comment by Johann150** [comment]
I think this is an issue with the `keep-alive` and/or the modal navigation. If you change step 4 to "close the modal, then go back to the federation tab", it does show the correct information for other instances after step 5.

https://github.com/misskey-dev/misskey/blob/1c38c7010d9a9604df979faa867cd8f9e7d825c9/src/client/components/modal-page-window.vue#L16-L18

Maybe the current `this.component` needs to be destroyed/unloaded when navigating back here?

https://github.com/misskey-dev/misskey/blob/1c38c7010d9a9604df979faa867cd8f9e7d825c9/src/client/components/modal-page-window.vue#L142-L144

***

I also noticed when scrolled down, that the chart is not loading properly because the `args.host` variable for `MkChart` is not properly defined. You should add ` :args="{ host }"` to `MkChart` in `src/client/pages/instance-info.vue`.

**Comment by Johann150** [comment]
To add to the above, this only happens with the `/admin` link from the menu bar, if it is opened with the `modalWindow` behaviour, i.e. if https://github.com/misskey-dev/misskey/blob/1c38c7010d9a9604df979faa867cd8f9e7d825c9/src/client/ui/classic.header.vue#L92

**Comment by Johann150** [comment]
I can not reproduce this problem any more with the current release when opening the federation panel in a window. Can you check if it works for you?

The chart problem was solved with d8905a9588f3d1c2d7112993c1b842a31f4d9a74.

**Comment by Johann150** [comment]
I can not reproduce this any more, I think it got fixed a while ago.
