### ISSUE TITLE
Error in initializing misskey in docker

### ISSUE THREAD

**Issue by KormiMeiko** [syuilo/Misskey#7990]
## 💡 Summary
so how to skip the configuration of ehostunreach?

ehostunreach connection error
## 🙂 Expected Behavior
success

## ☹️ Actual Behavior
it shows：

```
yarn run v1.22.5
$ npm run migrate

> misskey@12.95.0 migrate
> ts-node ./node_modules/typeorm/cli.js migration:run

Error during migration run:
Error: connect EHOSTUNREACH 172.18.0.3:5432
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1142:16) {
  errno: -113,
  code: 'EHOSTUNREACH',
  syscall: 'connect',
  address: '172.18.0.3',
  port: 5432
}
```
**But I don't want to use ehostunreach, so how to skip the configuration of ehostunreach?**

## 📌 Environment
CentOS8.2

**Comment by ybw2016v** [comment]
5432 is the default port of Postgresql and the information it shows  means that there might be someting wrong while connecting to Postgresql. 
I never heard any services or software whose name is **ehostunreach**…… It might mean `ehost-unreach`.

**Comment by yitsushi** [comment]
`EHOSTUNREACH` is TCP error and it means: No route to host.

Based on the error message:

migration (`during migration run`) can't connect to the postrgresql database (host: `172.18.0.3`; port: `5432`), but it was not able to connect because the target host is not available (`EHOSTUNREACH`).

* Is your postgresql database running? 
* It tried to use `172.18.0.3` as postgresql database, is the address right?

**Comment by akaregi** [comment]
Maybe *firewalld* causes `EHOSTUNREACH` error. It happens when firewalld  blocks inter-container networking.
ref: https://github.com/firewalld/firewalld/issues/844

Its error might be specific to openSUSE(see the issue) and RHEL series, includes CentOS, Oracle Linux(I use it), and more. So this doesn't belong to Misskey but OS-level. 

Solution is, adding NAPT rules to firewalld/iptables.
ref: https://genchan.net/it/virtualization/docker/12786/ (An article in Japanese)

----

firewalld がコンテナ間通信を阻害するために `EHOSTUNREACH` エラーが出てくるものと思われます。これはおそらく Misskey 自体のバグや Docker の設定(e.g. docker-compose.yml) によるものではなく OS レベル（firewalld/iptables）の設定によって起こります。このエラーは少なくとも RHEL 系（CentOS や 私の使っている Oracle Linux）や openSUSE 系のディストリで起きます。

解決策は Docker のために NAPT に関する規則を firewalld に教えてやることです。私の環境では英文側にある記事の設定をそのまま通すことで同様のエラーを解決しましたが、これが最善策なのかはわかりません。
