### ISSUE TITLE
svgをアップロードしたらwebpublic/thumbnailとしてpngを生成する

### ISSUE THREAD

**Issue by tamaina** [syuilo/Misskey#8097]
## Summary
svgを直接表示するのはセキュリティ的に問題があるが、svgをアップロード・表示できないのも不便なので、webpublicやthumbnailとしてpngを表示させるのが便利そう

**Comment by Johann150** [comment]
I think in many cases it would be more efficient to display SVGs directly instead of rasterizing them, because the file size can be smaller. Thus it would be better to scrub the security risks like JavaScript from the SVG image, or look into ways of displaying SVGs securely by e.g. using [Content Security Policy](https://developer.mozilla.org/docs/Web/HTTP/Headers/Content-Security-Policy).

**Comment by Johann150** [comment]
maybe this article is also interesting on this topic: https://digi.ninja/blog/svg_xss.php
