### ISSUE TITLE
Setting instance information of notes to always show breaks the timeline

### ISSUE THREAD

**Issue by ghost** [syuilo/Misskey#8205]
## 💡 Summary

I tried setting the option "Instance information of notes" to always show, but this seems to break the timeline. Upon loading the timeline, no posts load on Home, and I'm not able to switch to any other timeline.

## 🙂 Expected Behavior

Posts show normally in the timeline and local notes display instance information.

## ☹️ Actual Behavior

Timeline posts don't load at all. Timeline selection buttons are unresponsive.

## 📝 Steps to Reproduce

1. set "Instance information of notes" to Always show
2. press OK in the pop-up "this requires a reload"
3. go to home timeline

## 📌 Environment

Misskey 12.103.1
browser: Brave

**Comment by Johann150** [comment]
`Uncaught TypeError: props.instance is undefined` can be seen on the console. I think this is because for local users, the instance data is not set.

**Comment by Johann150** [comment]
I think this issue was introduced in 21c9705a0f947bf6e3900052987695c67f2d7510. The props definition needs to be fixed, and I think the instance should be made optional. This would in turn mean that there must be a null coercion for `instance`. If it is null it must be replaced by the local instance's data.
