### ISSUE TITLE
Max text size

### ISSUE THREAD

**Issue by ThatOneCalculator** [syuilo/Misskey#8241]
## 💡 Summary

If someone makes a post or chat with `$[x4 $[x4 $[x4 $[x4 $[x4 Content]]]]]` it becomes absolutely massive, taking up most of the screen.  

## 🙂 Expected Behavior

The text should be prevented from becoming larger.

## ☹️ Actual Behavior

It takes up the whole screen

![Screenshot_2022-01-31-11-08-25_2560x1440](https://user-images.githubusercontent.com/44733677/151926283-b6ff6c5f-6d9c-4de0-93bd-ffe80d814eff.png)

**Comment by Johann150** [comment]
I think https://github.com/misskey-dev/mfm.js/pull/87 already partially fixes this. I'm not sure how exactly it is feasible to limit the text size. But I think what would be useful in this case if the "show more" button was also used for cases like this.

**Comment by ThatOneCalculator** [comment]
> I think [misskey-dev/mfm.js#87](https://github.com/misskey-dev/mfm.js/pull/87) already partially fixes this. I'm not sure how exactly it is feasible to limit the text size. But I think what would be useful in this case if the "show more" button was also used for cases like this.

Maybe on Misskey web, make it so `$x2`/`$x3`/`$x4` can only be used once or twice in a single part of a mfm string?
Kinda a bad explanation, but basically

`Hello, $[x4 $[sparkle $[x4 Misskey!]]] How's everyone $[tada $[x4 $[x4 $[x4 doing today??]]]]`
would automatically turn into
`Hello, $[x4 $[sparkle Misskey!]] How's everyone $[tada $[x4 doing today??]]`

**Comment by futchitwo** [comment]
An alternative is to use CSS to limit the maximum size.

**Comment by Johann150** [comment]
Would that not be difficult to do if we also want to ensure a responsive design?

**Comment by ThatOneCalculator** [comment]
> Would that not be difficult to do if we also want to ensure a responsive design?

Yea. I think just limiting the amount of `$x[2,3,4]`s that are rendered is way easier.

**Comment by futchitwo** [comment]
> Would that not be difficult to do if we also want to ensure a responsive design?

For example, currently the `font-size` of $[x4] is `600%`, how about changing it to `min(600%,10rem)`? I don't think this will affect responsive design.

**Comment by ThatOneCalculator** [comment]
> > Would that not be difficult to do if we also want to ensure a responsive design?
> 
> For example, currently the `font-size` of $[x4] is `600%`, how about changing it to `min(600%,10rem)`? I don't think this will affect responsive design.
> 

Great idea! Cc @syuilo

**Comment by syuilo** [comment]
The essence of the problem is that "See More" does not work in these cases, so it would be better to fix that.

**Comment by Johann150** [comment]
Since the choice to collapse a note is made in the setup script, something like checking the rendered height becomes difficult because it is not available at setup time. And collapsing a note after rendering might also cause unpleasant flashing.

Just limiting the height of a note might hide some content for long notes with normal text size. However that is not what misskey is designed for anyway and for the cases where this happens we could instead use an additional "Show More" button that appears after e.g. the screen height that leads to the respective `note-detailed.vue` instead of expanding on the timeline. This could also be done in CSS only I think.

Or of course the suggestion of limiting certain elements might also be a good idea, but I'm not sure if it is easily possible to catch all cases (e.g. can font be enlarged with KaTeX?).

**Comment by Johann150** [comment]
> An alternative is to use CSS to limit the maximum size.

I think an easier way to implement this using CSS would be to use CSS classes instead of inline style. Then we could do for example:
```css
.mfm-x4 {
    font-size: 600%;
}
.mfm-x4 .mfm-x4 .mfm-x4 {
    font-size: 100%;
}
```
Or it would at least enable users to do something like this with custom CSS so I think at least using CSS classes instead of inline styles is a good idea.
