### ISSUE TITLE
Clip page has default favicon

### ISSUE THREAD

**Issue by ThatOneCalculator** [syuilo/Misskey#8265]
## 💡 Summary

`instance.tld/clips/whatever` shows the default Misskey favicon, not the set one.

(See screenshot of https://stop.voring.me/clips/8wgtnk4aps vs https://stop.voring.me/)
![Screenshot_2022-02-07-02-39-26_2560x1440](https://user-images.githubusercontent.com/44733677/152884465-f933a2aa-5f23-45ab-b0db-ee461504b6f5.png)

## 🥰 Expected Behavior

Tab has instance favicon

## 🤬 Actual Behavior

Tab has default favicon

## 📌 Environment

Misskey version: 12.103.1 (development)
Your OS: Linux
Your browser: Firefox

**Comment by Johann150** [comment]
The issue seems to be that some templates are missing the `icon` variable when rendering the pug templates. These should be specified like this https://github.com/misskey-dev/misskey/blob/b267a504ca4563e042929198319273e969939fc9/packages/backend/src/server/web/index.ts#L330

I think this would not only be the case for clip pages, but I think the icon was also missing for other pages.

**Comment by ThatOneCalculator** [comment]
Fixed by #8270

**Comment by Johann150** [comment]
Normally the issue is closed when the PR is merged, so you don't have to close it manually. 👍

**Comment by ThatOneCalculator** [comment]
> Normally the issue is closed when the PR is merged, so you don't have to close it manually. +1

Ah gotcha! My bad.

**Comment by robflop** [comment]
Specifically, for a PR to close an issue it has to contain "closes \<issue\>" or "fixes \<issue\>" in the body and get merged, afaik.
