### ISSUE TITLE
モデレーターはブロックされていても投稿を見れるようにする

### ISSUE THREAD

**Issue by syuilo** [syuilo/Misskey#8278]
## Summary

モデレーションに支障を来す

ref https://github.com/misskey-dev/misskey/issues/7898

**Comment by tamaina** [comment]
SAME AS #7734

**Comment by Johann150** [comment]
I saw that there was a lot of discussion in the linked issues, but I could not read it all because I don't speak Japanese so sorry if I missed something.

I think to avoid the concerns about moderators/administrators seeing everything by default we could implement something like soft mutes, e.g. the client shows a message like "User {xyz} said something private, click to see anyway." and only when the moderator/admin clicks on it, the content is shown.

In the backend, the visibility check(s) of notes would have to be adjusted to let moderators/administrators see all notes.

**Comment by rinsuki** [comment]
merge to https://github.com/misskey-dev/misskey/issues/7734
