### ISSUE TITLE
Allow moderators to block instances / Multiple admins

### ISSUE THREAD

**Issue by turtlegarden** [syuilo/Misskey#8344]
## Summary
Add the instance block privilege to moderators
## Why?
Allowing moderators to block instances could speed up removal of content harmful to the users.

**Comment by absturztau-be** [comment]
in that case, it might be better to have a 3rd role (apart from admin and mod) that could do that. because depending on how you want to run your instance, you kinda want to have the moderator role, that isn't able to instance block. just my thoughts on that

Edit: or to have the option to promote a user to an admin

**Comment by ThatOneCalculator** [comment]
Maybe 

- Mod (suspend/silence/delete/etc)
- Staff (everything mod has + control other instances)
- Admin (admin)

**Comment by turtlegarden** [comment]
That would be a good idea. For instances where the admin isn't too active (mine, to name one), there can be "co-admins" who can control the blocklist.

**Comment by Johann150** [comment]
Especially from the last comment it sounds like this could just be accomplished by using the existing Moderator & Administrator roles.
I don't really see why the big added complexity of an additional role would be justified.

**Comment by absturztau-be** [comment]
> Especially from the last comment it sounds like this could just be accomplished by using the existing Moderator & Administrator roles.

yes, but we need to be able to add the admin role to a user then

**Comment by ThatOneCalculator** [comment]
So essentially, the instance owner should be able to assign other people admin

**Comment by foreverxml** [comment]
kinda, but not really
Doesn't need all the admin features, just instance block privileges

**Comment by Johann150** [comment]
> yes, but we need to be able to add the admin role to a user then

This is already possible, but not in the web UI because of the wide reaching consequences. Please use `packages/backend/built/tools/mark-admin.js` e.g. like this
```shell
node packages/backend/built/tools/mark-admin.js other_admin
```

> Doesn't need all the admin features, just instance block privileges

As I said I don't think this specific use case would justify adding a specific role, and as also already said allowing moderators to block instances is also not desirable.

**Comment by futchitwo** [comment]
related
- #6305

**Comment by turtlegarden** [comment]
I'll close this for now then. 😕
