### ISSUE TITLE
公開範囲:ダイレクトで投稿した時に、宛先を後からわかるようにしてほしい

### ISSUE THREAD

**Issue by na2na-p** [syuilo/Misskey#8414]
## Summary

現状は、ダイレクト投稿で送信した後に誰に対してノートを送信したのかわからないので、あとからわかるようにしてほしい。
![image](https://user-images.githubusercontent.com/49822810/158538105-4f5e80e7-3164-49be-ba80-0429ad76e72c.png)
![image](https://user-images.githubusercontent.com/49822810/158538254-3958e533-0f16-49d5-9563-10cf393d7801.png)

**Comment by Johann150** [comment]
The backend already reports this in `visibleUserIds`. You will already see them added to the recipients list when you reply to a note.

I don't know where it would be best for the client to display this information otherwise, as it is in theory separate from who was mentioned. Maybe as a menu option, but the menu is already quite full.

**Comment by Johann150** [comment]
Another idea would be to show it when hovering over the envelope symbol.

**Comment by syuilo** [comment]
> Another idea would be to show it when hovering over the envelope symbol.

nice

**Comment by futchitwo** [comment]
チャンネル投稿のチャンネル名表示のように、ノートのフッター(もしくはヘッダー)に表示するのも良さそう
