### ISSUE TITLE
antennae not respecting instance mutes

### ISSUE THREAD

**Issue by nbsp** [syuilo/Misskey#8432]
## 💡 Summary

notes from instances in the "muted instances" list show up in antennae

## 🥰 Expected Behavior

an antenna should not look for posts from instances in the mute list

## 🤬 Actual Behavior

posts from muted instances show up on the antenna timeline

## 📝 Steps to Reproduce

1. create an antenna
2. add an instance to the mute list
3. make a post that matches the antenna, from that instance

## 📌 Environment

Misskey version: 12.108.1
Your OS: N/A
Your browser: N/A

**Comment by Johann150** [comment]
It seems that #7712 did not add the respective query generation in all necessary places, and I think it affects more places than antennas. I think we could merge the query generation `backend/src/server/api/common/generate-muted-instance-query.ts` &rarr; `backend/src/server/api/common/generate-muted-user-query.ts`.
Alternatively we have to check every place where notes are delivered over the API because I think this might not be limited to antennas.

**Comment by Johann150** [comment]
related about not respecting user level mutes would be #8417
