### ISSUE TITLE
Can't use non latin characters in username

### ISSUE THREAD

**Issue by DeMiro5001** [syuilo/Misskey#8503]
In the username creation, can't use Arabic or Japanese characters. I don't know if it's on purpose or a bug.

**Comment by acid-chicken** [comment]
AFAIK this is the expected behavior, but there may be room for discussion on this spec., especially since I don't recall discussing it at the time of the decision (#1294).

Note for developers, [RFC 7565 allows the use of non-Latin characters with percent encoding](https://datatracker.ietf.org/doc/html/rfc7565#section-7), so if the user name can be parsed on Misskey, there should be no particular problem with federation (as long as the server to be federated is implemented correctly).

**Comment by Johann150** [comment]
I'm not sure if it is a good idea to allow this, as it might lead to federation problems for those accounts. Other Fediverse does not allow this either as far as I understand, see e.g. https://github.com/mastodon/mastodon/issues/6830.

**Comment by acid-chicken** [comment]
As for me, I'm neither for nor against usability of non-Latin characters in the username of Misskey at this point.

Anyway, the spec of username in implementations (e.g. Mastodon)  can be the subset of the RFC 7565’s userpart, so the unavailability of some characters in the implementation’s usernames is not a problem. However, it seems to me that the inability to mentions is more like an implementation bug.
In domain names, non-Latin characters can be used by punycode anyway, but it is up to the implementation to decode them. However, if it itself cannot be handled, then that is an implementation problem. The same could be said for the percent encoding of usernames.

**Comment by tamaina** [comment]
I understand that there seems to be no problem with the technical specifications.

However, I think that allowing all Unicode characters is problematic as it enables spoofing by using similar characters or zero-width spaces.

**Comment by acid-chicken** [comment]
> However, I think that allowing all Unicode characters is problematic as it enables spoofing by using similar characters or zero-width spaces.

Yes, it's also a problem. Not decoding would be a simple countermeasure, but may affect the usability. Alternatively, not decoding unsafe characters, as in the idea of microsoft/vscode#136437, could be a countermeasure.

**Comment by acid-chicken** [comment]
Of course, in Misskey usernames, we can simply forbid those characters.

**Comment by Johann150** [comment]
> However, I think that allowing all Unicode characters is problematic as it enables spoofing by using similar characters or zero-width spaces.

This is also what I meant. But from further reading of the linked RFC, this is also a requirement by it, see section 6 of RFC 7565:

> - The `userpart` consists only of Unicode code points that conform to the PRECIS IdentifierClass specified in RFC7564.

Note: ~~RFC 7564~~ was replaced by RFC 8264.

Because it is a RFC, maybe there already exists a library for handling strings like this? Then we should implement it so that only the normalized form of the account name will be used by the backend.

**Comment by tamaina** [comment]
I would like to limit username to Latin letters *for reasons of atmosphere, sensitivity and design*.

**Comment by syuilo** [comment]
The reason for having username separate from the user's "name" is to create an alias that can be easily typed into the account. Allowing characters other than [a-zA-Z0-9_] loses that advantage. If we were to change the character set, it would be a not small breaking change. It would also create encoding problems and other headaches.

**Comment by Johann150** [comment]
If we agree this is not a good idea, this can be closed.

You can use non latin characters in your display name if you want.
