### ISSUE TITLE
Wrong following and follower count in profile

### ISSUE THREAD

**Issue by ghost** [syuilo/Misskey#8516]
## 💡 Summary

Following and follower count is different. See screenshots.

![20220417-1716](https://user-images.githubusercontent.com/58190287/163720932-177cd0d9-3143-4a5d-9386-2e390e548e5c.jpg)

![20220417-1717](https://user-images.githubusercontent.com/58190287/163720934-a9c885ac-1a0a-4e19-8b9c-8ef3eb32c188.jpg)

Misskey version: 12.110.0
Your OS: Debian 10 Buster

**Comment by Johann150** [comment]
This is similar to #7208 and can also apply to the notes count: The number of notes, followers, and followed is cached in the `user` database table, but this can sometimes get out of sync from the actual numbers.
The `More > Account Info > Statistics` are generated by actually counting the objects in the database so they do not suffer from this problem and are more reliable.

As far as I can see the code to follow and unfollow should be keeping track of these statistics correctly so I am not sure when the numbers get out of sync. I think the problem is that the `increment` and `decrement` calls need to be `await`ed to ensure they finish properly:
https://github.com/misskey-dev/misskey/blob/d338ea2591f724e485aa84c824268371e77a6ad4/packages/backend/src/services/following/create.ts#L69-L72
https://github.com/misskey-dev/misskey/blob/d338ea2591f724e485aa84c824268371e77a6ad4/packages/backend/src/services/blocking/create.ts#L100-L106
https://github.com/misskey-dev/misskey/blob/d338ea2591f724e485aa84c824268371e77a6ad4/packages/backend/src/services/following/delete.ts#L61-L67
