### ISSUE TITLE
"File too large" error formatted incorrectly

### ISSUE THREAD

**Issue by ThatOneCalculator** [syuilo/Misskey#8574]
## 💡 Summary

The "File too large" error has incorrect formatting

## 🥰 Expected Behavior

Correctly formatted error

## 🤬 Actual Behavior

![20220429_182817280_c2a1.jpg](https://user-images.githubusercontent.com/44733677/166085354-fba80642-ccbe-4581-8b24-0bdda69045e2.jpg)

## 📝 Steps to Reproduce

1. Go to drive
2. Upload too large file 

## 📌 Environment

Misskey version: 12.110.1
Your OS: iOS
Your browser: Chrome

**Comment by Johann150** [comment]
To fix this, the code below should show a respective error message instead of the current one (`text`) if the 413 response status code is detected. A new internationalization string would need to be added.

https://github.com/misskey-dev/misskey/blob/d3e242a7f25e72bd65f27feebd878f5a45e7ae3b/packages/client/src/scripts/upload.ts#L86-L90

Would be nice to also fix the `title` to also be internationalized instead of hard coded as English in the process.

**Comment by tinaxd** [comment]
In the current develop branch, if the server returns 413 with a non-JSON response, no error is displayed on the frontend because the JSON parsing fails and an uncaught exception is raised.
https://github.com/misskey-dev/misskey/blob/8dc60cd3273be7103050bb8e680db03f2856cec3/packages/frontend/src/scripts/upload.ts#L82-L88
As @Johann150  mentioned, we can solve this by displaying a user-friendly error message when status code 413 is detected.
May I start working on this issue?
