### ISSUE TITLE
GenerateVideoThumbnail failed: TypeError: FFmpeg is not a function

### ISSUE THREAD

**Issue by tastytea** [syuilo/Misskey#8693]
## 💡 Summary

Thumbnails for videos I upload or receive are not generated. I get this in the logs:

```
WARN 1   [drive register]        GenerateVideoThumbnail failed: TypeError: FFmpeg is not a function
```

I can manually generate a thumbnail with `ffmpeg` on the server with:

```
ffmpeg -i video.webm -frames:v 1 thumbnail.jpeg
```

## 🥰 Expected Behavior

Thumbnail is generated

## 🤬 Actual Behavior

No thumbnail is generated

## 📝 Steps to Reproduce

1. Upload video
2. No thumbnail

## 📌 Environment

Misskey version: 12.110.1
Your OS: Gentoo Linux
Your browser: Firefox 91.9.0esr

**Comment by Johann150** [comment]
Can you check all necessary dependencies are installed by running `yarn install` (or `npx yarn install` if you have not installed yarn)?

**Comment by tastytea** [comment]
Looks alright to me…

``` shellsession
% sudo -u misskey yarn install
yarn install v1.22.19
[1/4] Resolving packages...
success Already up-to-date.
$ node ./scripts/install-packages.js
installing dependencies of packages/backend ...
yarn install v1.22.19
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.67s.
installing dependencies of packages/client ...
yarn install v1.22.19
[1/4] Resolving packages...
success Already up-to-date.
Done in 4.69s.
Done in 7.12s.
```

**Comment by Johann150** [comment]
Neither [the usage](https://github.com/misskey-dev/misskey/blame/develop/packages/backend/src/services/drive/generate-video-thumbnail.ts#L15) nor [the import](https://github.com/misskey-dev/misskey/blame/develop/packages/backend/src/services/drive/generate-video-thumbnail.ts#L4) nor [the npm module that supplies `FFmpeg`](https://www.npmjs.com/package/fluent-ffmpeg) have been altered since 2019, so I'm not sure what has changed that makes it not work any more.

Does the log contain any more information about the error, maybe a stack trace?

**Comment by tastytea** [comment]
No, just

```
INFO 1  [drive register]        {"size":609679,"md5":"347e14e838f52f704e9adeb735ea7dd7","type":{"mime":"video/webm","ext":"webm"},"warnings":[]}
WARN 1  [drive register]        GenerateVideoThumbnail failed: TypeError: FFmpeg is not a function
DONE 1  [drive register]        drive file has been created 90dmcjlqwl
```

Can I increase the debuglevel or do something to get more information?

**Comment by tamaina** [comment]
esmが問題になっていると私は思う

**Comment by mei23** [comment]
> esmが問題になっていると私は思う

せいかい
https://github.com/misskey-dev/misskey/pull/8696

**Comment by tastytea** [comment]
I can confirm it works here. Thank you! :sparkling_heart:
