### ISSUE TITLE
'hs2019'  for HTTPSignatures

### ISSUE THREAD

**Issue by sthaydn** [syuilo/Misskey#8730]
Hi there,

when connecting to another fediverse software called "streams" (the successor to ZAP) I can't send from streams to misskey. Misskey to streams works. The dev of streams wrote me:

"Chances are pretty good that they don't support 'hs2019'  for HTTPSignatures per the most recent version of that draft specification, or they don't support it correctly."

Is this implemented?

Regards,

Stefan

**Comment by Johann150** [comment]
The "hs2019" currently has an open PR because we also had federation issues with e.g. Owncast, see #8635.

Regarding the "per the most recent version of that draft" formulation: Please note that Misskey will use the same version of `hs2019` that Mastodon uses because most other software seems to use it. That version is not the "most recent version of that draft", because using that version would break federation again. For Misskey, `hs2019` will mean the same as `rsa-sha256`.

**Comment by sthaydn** [comment]
I see. Thanks for your explanation. I don't know what all this means, but when reading #8635 it seems you are aware of the topic, so this could be closed then.
