### ISSUE TITLE
MFM in bios doesn't federate

### ISSUE THREAD

**Issue by ThatOneCalculator** [syuilo/Misskey#8742]
## 💡 Summary

My bio has MFM, but it doesn't show on other instances

## 🥰 Expected Behavior

MFM federates in bios

## 🤬 Actual Behavior

Local:

![image](https://user-images.githubusercontent.com/44733677/170595059-cedbd009-34d1-4cce-857d-f06d454b3f4d.png)

Remote:

![image](https://user-images.githubusercontent.com/44733677/170595076-833c258b-3eb7-4382-b05e-7ed61d758445.png)

![image](https://user-images.githubusercontent.com/44733677/170595085-c70ad76f-fed8-4259-b3cb-b15416293aba.png)

## 📌 Environment

Misskey version: All 12.110.1
Your OS: Firefox
Your browser: Linux

**Comment by pixeldesu** [comment]
At the current time, I don't think this is a good idea.

Even if this is probably just meant between Misskey instances, without adding a new field for bio content (please no `_misskey_content`), we would need to use standard field that other software will also look for.

Now, if software does not sanitize the HTML and leaves the attributes as they arrive, there is some risk of MFM breaking some parts of the UI because of the inline styles for animations. If MFM only set classes that Misskey defines the animations for this wouldn't be an issue, but that's not the case at the moment (and I'm not even sure if this is desired/planned).

**Comment by futchitwo** [comment]
duplicate of #4810 ？

**Comment by ThatOneCalculator** [comment]
Yep.
