### ISSUE TITLE
GitHubやめる

### ISSUE THREAD

**Issue by tamaina** [syuilo/Misskey#8886]
Quit GitHub

## Summary
@ThatOneCalculator が凍結されたところ、彼の貴重なIssue/PRやコメントが消え、本リポジトリのディスカッションに著しい不便を強いられることとなった。  
（せめて別のアカウント（ghostなど）に振り替えるとかをしてほしいんだけど…）

これを機に、GitHubやめてGitサービス (GitLab とか？) をセルフホスティングするのはどうだろうか。

余談: Gitセルフホストサーバーソフトウェアのくせに自分のコードはGitHubで管理してるプロジェクトって…なんなん？

**Comment by rinsuki** [comment]
suspendなのでたぶん不可視だけどまあ

**Comment by rinsuki** [comment]
https://stop.voring.me/notes/91vmznf7mu

hidden from public だね

**Comment by tamaina** [comment]
unsuspendされるかどうかはGitHub運営の一存であってunsuspendされないかもしれないし、suspendされている間はとにかく不便なのは変わりない

**Comment by acid-chicken** [comment]
開発に影響が出てるならとりあえず GitHub に影響が出て困ってる旨を連絡するのが先な気もする

**Comment by rinsuki** [comment]
> 開発に影響が出てるならとりあえず GitHub に影響が出て困ってる旨を連絡するのが先な気もする

書くの忘れてたけどやった

**Comment by acid-chicken** [comment]
> > 開発に影響が出てるならとりあえず GitHub に影響が出て困ってる旨を連絡するのが先な気もする
>
> 書くの忘れてたけどやった

ありがとう
ならとりあえず返事待ちかなぁ

**Comment by tamaina** [comment]
私も support.github.com/contact に送ってみた

**Comment by KainoaKanter** [comment]
Hi everyone! It's @thatonecalculator, I made this account specifically with my university email as a student account, so it shouldn't violate the ToS of Github. Proof: https://stop.voring.me/notes/91wcotqgsb

After what happened, I personally feel that relying on Github is a risky move going forward. While it is immensely popular, I agree with tamania in that we should look into alternatives, perhaps [Codeberg](https://codeberg.org/) who provides free CI for FOSS projects. All my issues and pull requests are wiped from my visibility, and I don't even know if Github will get back to me and reinstate my account, as they've been very unresponsive.

**Comment by Johann150** [comment]
I am currently taking a look at Codeberg but I think we would need to host CI ourselves, although integration should be possible. I'm currently looking into that.

**Comment by KainoaKanter** [comment]
We don't *need* to host the CI, just have to apply for access :) 
https://codeberg.org/Codeberg-CI

**Comment by KainoaKanter** [comment]
Also, they have a very nice implementation of migration which I've already started to use for my own projects.

![image](https://user-images.githubusercontent.com/108149780/175662551-46657099-41e0-4bd0-ae3b-2086fa86aa9b.png)

**Comment by rinsuki** [comment]
I actually have a my Gitea just for backup, but I don't like Gitea (which is what Codeberg uses) design, like unnecessary animation, some (weird) paddings, miss-aligned texts, etc...

it would be good if @syuilo writes a theme for Gitea, or create completely new git hosting service instead, since @syuilo design is pretty cool 😎

**Comment by KainoaKanter** [comment]
Syuilo already has his hands full with Misskey, codeberg improves on the gitea UI already but it can be modified locally as well. I don't think it's an issue of appearance of a web ui, rather that of Github having extremely detrimental moderation practices.

**Comment by Johann150** [comment]
In my opinion it sounds like a good idea to switch. Changing the theme could be done later.

**Comment by KainoaKanter** [comment]
(Unofficial) poll link: https://stop.voring.me/notes/91whxwjn1a

Edit: even within 20 minutes, that's an ***overwhelming*** majority.

![Screenshot of poll, 25 yes to 4 no](https://user-images.githubusercontent.com/108149780/175670415-13ad0feb-be8e-460e-9ef7-4a06e2df638a.png)

**Comment by KainoaKanter** [comment]
@syuilo @tamaina @Johann150 It seems like ~85-90% of people are voting that Misskey should move to Codeberg. I think perhaps a slow transition sometime soon would be a good idea, thoughts?

**Comment by rinsuki** [comment]
> Syuilo already has his hands full with Misskey

sadly yes...

> codeberg improves on the gitea UI already but it can be modified locally as well.

I'm not sure about codeberg improves (they have a customized header, but do you know about other changes?) and Gitea's CSS are big and patch by UserCSS is pretty hard for some cases. (disable animation is pretty easy and I'm doing now, but change some padding or other things are maybe hard and/or long way)

I want to say Codeberg is not a only way; we should check another ways, like GitLab (pretty slow though), Gitea with better themes (if exists),  or other hosting services, and more.

**Comment by KainoaKanter** [comment]
I agree. Codeberg is definitely *not* the only option, but seems like one of the better ones, especially because of the free CI/CD. Also, I use [gitea-modern](https://userstyles.world/style/529/gitea-modern) for Codeberg :)

**Comment by marihachi** [comment]
まず、GitHubは他のプラットフォームより一般的だと思います。
各自のGitHub上での当たり前の行動(荒らし行為をしないなど)を留意すれば、GitHubを使うのも特に問題はないと思います。
今回の件で、GitHubは悪くない。悪いのはユーザーの態度です。

**Comment by KainoaKanter** [comment]
It's not about whether they suspended me or not (that's their moderation decision), it's moreso about how willing Github is to erase a bunch of work and break currently in-progress projects (I had multiple PRs and issues open), and then not even respond to phone calls, emails, or support tickets.

**Comment by PikaDude** [comment]
> It's not about whether they suspended me or not (that's their moderation decision), it's moreso about how willing Github is to erase a bunch of work and break currently in-progress projects (I had multiple PRs and issues open), and then not even respond to phone calls, emails, or support tickets.

Personally I've never seen GitHub suspend an account before in all my years of using GitHub. You did *willingly* violate GitHub's agreement with you and their service (on a federal-owned repository at that) several times in a short space of time, so they terminated it as a whole. You embarrassed yourself, and likely GitHub too.

I don't believe there are any real issues with using GitHub, and a poll from users of the software is meaningless in contract to a poll of the contributors and developers of the software, as ultimately there are no major effects of where the source code is hosted for users.

**Comment by acid-chicken** [comment]
> It seems like ~85-90% of people are voting that Misskey should move to Codeberg. I think perhaps a slow transition sometime soon would be a good idea, thoughts?

I don't know how to say this about an informal survey, but is this survey really meaningful?
At the time I looked at the survey, there were 112 votes (I did not vote), while 33 contributors have committed to the repository in the last year (thank you). So, even if all active contributors had participated in the poll, it is clear that the number of votes from non-active contributors is overwhelmingly greater than that of active contributors.
I am not saying that they should contribute, but it finally doesn't make sense that those who don't contribute are causing inconvenience to our members and those who do contribute. However, if a self-hosted alternative Git server is clearly more convenient than GitHub, I would be happy to hear about it.

**Comment by KainoaKanter** [comment]
While I agree that the git server is very important for contributors, we should also keep the peace-of-mind of the end users (instance admins) in consideration. If Github can actively censor data now, if even a small amount, what precedent does that set for the future of the repository? Relying on proprietary and centralized services like Github have already started to show their flaws. While I would say it's "clearly" more convenient, I believe the pros outweigh the cons.

**Comment by acid-chicken** [comment]
Git is a decentralized service. I'm not sure what you mean by cons, but if they won't contribute, a Git mirror server should be enough to access our code. If not, can you tell me what specific features would be a burden?

**Comment by PikaDude** [comment]
I wouldn't be alarmed of GitHub "censoring data" in regards to this repository because they deleted your comments harassing an individual.

**Comment by KainoaKanter** [comment]
It's not about the comments that were deleted (also on my account they're not deleted but marked as "spammy"), it's the issues and PRs that I've made on every other repo that's been censored.

**Comment by KainoaKanter** [comment]
> Git is a decentralized service. I'm not sure what you mean by cons, but if they won't contribute, a Git mirror server should be enough to access our code. If not, can you tell me what specific features would be a burden?

It's not about features that are a burden, it's more about having the code itself on a platform that's moderated by Microsoft. A mirror isn't enough to make issues and PRs.

**Comment by KainoaKanter** [comment]
> Personally I've never seen GitHub suspend an account before in all my years of using GitHub. 

I've seen maybe 5 or 6 suspensions? 2 of which were caused by me lol

**Comment by acid-chicken** [comment]
> It's not about features that are a burden,  it's more about having the code itself on a platform that's moderated by Microsoft.

Why does it matter where We put our code in an open source repository? As I said earlier, Git is decentralized, so no matter where the Git servers are located, essentially nothing changes. do you think someone at GitHub would arbitrarily impersonate us and inject malicious commits? The chances of that happening are much lower than the possible dangers of self-hosting, even if only for safety reasons. If there is a problem other than safety, what exactly is the problem? Are you saying that there is a privacy concern in just accessing public code?

> A mirror isn't enough to make issues and PRs.

If there are concerns about convenience for contributors, then the survey should be addressed to contributors. You don't have to use GitHub reactions, but a secret ballot is almost pointless because of the problems I mentioned earlier.

**Comment by Johann150** [comment]
Git *can be* decentralized in *theory*. But that would require someone to actually run a mirror for it outside of GitHub. (It should also include branches of remote repositories made for pull requests.) I am not aware of someone doing that.

But I think as you said, the code itself is not really the biggest issue here. Instead these are the actual issues:

> I can easily get all my project files, but how exactly would I …
>
> - Download the issue tracker (not the data, the service)?
> - Migrate my community?
> - HTTP 301 redirect all my backlinks?

-- https://raccoon.onyxbits.de/blog/why-not-use-github/

The code is not the only thing that is hosted on GitHub, and that is or can be a problem. My opinion is also that ThatOneCalculator's behaviour was inappropriate. But a few months ago we saw that many Russian GitHub users were suspended similarly with their pull requests and issues vanishing, even though I am quite sure that in many cases they did not do anything wrong themselves (see [this article](https://www.bleepingcomputer.com/news/security/github-suspends-accounts-of-russian-devs-at-sanctioned-companies/)). So in my eyes there are no guarantees that GitHub will not just suspend anyone for reasons they might not be able to influence, due to GitHub having to abide by laws of the USA.

**Comment by acid-chicken** [comment]
I'm not keen on breaking away from GitHub and moving to a self-hosted (but centralized anyway) Git server and issue tracker as I said earlier, but on the other hand, it would be interesting to have a distributed system with ActivityPub for issue trackers.

**Comment by Johann150** [comment]
> a distributed system with ActivityPub for issue trackers

[Gitea is moving in that direction](https://discourse.gitea.io/t/milestones-for-federation-grant/4895/4) and is much more likely to implement it than GitHub...

**Comment by acid-chicken** [comment]
> > a distributed system with ActivityPub for issue trackers
> 
> [Gitea is moving in that direction](https://discourse.gitea.io/t/milestones-for-federation-grant/4895/4) and is much more likely to implement it than GitHub...

That is interesting; go-gitea/gitea#18240. It would be nice to be able to participate in Issues from Misskey or Mastodon, etc., as one of the concerns is that we don't want to add more platforms to receive notifications, etc.

**Comment by n0toose** [comment]
> I don't believe there are any real issues with using GitHub

> Why does it matter where We put our code in an open source repository?

Hi, I am not a contributor, but I have had some experience with GitHub as a maintainer and I am very interested in Misskey, as well as other projects revolving around federation, even though I do not possess the required skills to contribute right now. I'd like to share a few thoughts because I believe that I can contribute to the conversation (as someone who has field-tested GitHub to its limits on accident and not as a preacher). I wrote ~a 100000 word breakdown~ some notes on this topic, which come from concerns from the perspective of an average user/maintainer: https://n0toose.net/posts/move-away-from-github/ (Sorry for the plug, it's just that I wrote a post on this as this conversation pops around very often, like on here.)

This topic being discussed here has been extensively analyzed by other people in this space; you can find some additional propaganda available for consumption here: https://drewdevault.com/2022/03/29/free-software-free-infrastructure.html

(An important concern against Gitea is that it's inaccessible to people using screen readers [according to a mutual who is blind], which should be important.)

**Comment by KainoaKanter** [comment]
Here's my thoughts on all this:

I think it would be wise for this project (and its adjacent misskey-dev projects) to move to *some* other git service. However, it's not without its downsides.

# Staying on Github

### Benefits

- Keep stars
- High visibility

However, these benefits aren't that large if the Github repo can still be used to redirect users to another git server

### Downsides

- Github's moderation policy 
    - > My opinion is also that ThatOneCalculator's behaviour was inappropriate. 

        I entirely agree, and I showed my apologies and remorse for my behavior in a support ticket which has yet to be read, and I doubt will ever be. It's not that they took moderation against me, it's that they moderated me in such a way that it erased history and harmed other, innocent users and orgs on repos like Misskey who were processing my issues and pull requests.
- Github is a closed source, centralized service ***owned by Microsoft***. While I'm very biased and opinionated against Microsoft, from just an objective view Microsoft has and will always follow Embrace Extend Extinguish -- and with Github, we're in that second phase with things like copilot violating code licenses for the sake of "convenience" and rolling out even more closed source services.  I hope I don't have to explain why this is a bad thing.

# Moving to Gitea

## Either way...

### Benefits

- Potential of decentralization through ActivityPub
- Can migrate pretty much everything from GitHub
- More paid from Github for free -- not that Misskey really uses them
- Peace of mind that Misskey is on a Free and Open Source platform, no potential for corporate changes
-  More customizable
- No sale of personal data
- No Microsoft!

### Downsides

- Not screen-reader friendly (although that's being worked on)
- Harder discoverability(?)

## Moving to Codeberg

### Benefits

- Being on a free service
- Free CI (if Misskey applies and is accepted -- and is subject to change?)
- Free "pages" (like Github pages), will always be free of charge
- Responsibly hosted in the EU
- Reasonable moderation
- Free as in cost

### Downsides

- Not self-hosted (not that Github is either)
- No mirroring

## Self-hosting Gitea

### Benefits

- Full autonomy
- Zero chance of a third party intervening

### Downsides

- Even lower discoverability until Gitea federates
- Have to manage own infestructure
- Would cost money

**Comment by KainoaKanter** [comment]
Here's my thoughts on all this:

**I think it would be wise for this project (and its adjacent misskey-dev projects) to move to *some* other git service. However, it's not without its downsides.**

# Staying on Github

### Benefits

- Keep stars
- High visibility

However, these benefits aren't that large if the Github repo can still be used to redirect users to another git server

### Downsides

- Github's moderation policy 
    - > My opinion is also that ThatOneCalculator's behaviour was inappropriate. 

        @Johann150 I entirely agree, and I showed my apologies and remorse for my behavior in a support ticket which has yet to be read, and I doubt will ever be. The problem isn't that they took moderation against me, it's that they moderated me in such a way that it erased history and harmed other innocent users and orgs on repos like Misskey who were processing my issues and pull requests.
- Github is a closed source, centralized service ***owned by Microsoft***. While I'm very biased and opinionated against Microsoft, from just an objective view Microsoft has and will always follow Embrace Extend Extinguish -- and with Github, we're in that second phase with things like copilot violating code licenses for the sake of "convenience" and rolling out even more closed source services.  I hope I don't have to explain why this is a bad thing.

# Moving to Gitea

## Either way...

### Benefits

- Can migrate pretty much everything from GitHub
- More paid from Github for free -- not that Misskey really uses them
- Peace of mind that Misskey is on a Free and Open Source platform, no potential for corporate changes
-  More customizable
- No sale of personal data
- No Microsoft!
- Potential of decentralization through ActivityPub in the future

### Downsides

- Greater barrier of entry for (new) contributors
- Not screen-reader friendly (although that's being worked on)
- Harder discoverability(?)

## Moving to Codeberg

### Benefits

- Being on a free as in freedom and in price service
- Arguably *the* most trustworthy public Gitea instance
- Free CI (if Misskey applies and is accepted -- and is subject to change?)
- Free "pages" (like Github pages), will always be free of charge
- Responsibly hosted in the EU
- Reasonable moderation
- Since Codeberg is one of the larger Gitea instances, it might be more enticing for contributors, new and existing than to make a new account on a Gitea instance *just* for Misskey

### Downsides

- Not self-hosted (not that Github is either)
- No mirroring

## Self-hosting Gitea

### Benefits

- Full autonomy
- Zero chance of a third party intervening

### Downsides

- Even lower discoverability until Gitea federates
- Have to manage own infestructure
- Would cost money

**Comment by ThatOneCalculator** [comment]
Even though my account has been unsuspended, my thoughts are still the same that about staying on Github.

**Comment by Johann150** [comment]
The Software Freedom Conservancy recommends to stop using GitHub. Here is a Fediverse thread they made **today**: (link to the last entry so you can fetch the entire thread to your instance at once) https://mastodon.technology/@conservancy/108566700560938496 and they made a website: https://giveupgithub.org/

**Comment by Johann150** [comment]
Of course, the Free Software Foundation has recommended to not use GitHub for a while:
> Use an ethical repository for your hosting needs.
-- https://www.fsf.org/blogs/licensing/do-githubs-updated-terms-of-service-conflict-with-copyleft

> #### GNU Ethical Repository Criteria Evaluations
> [...]
> **github.com — F**
> [...]
> Here are [additional reasons to avoid github.com](https://sanctum.geek.nz/why-not-github.html).
-- https://www.gnu.org/software/repo-criteria-evaluation.html

**Comment by ThatOneCalculator** [comment]
@syuilo with all of this said, what are your thoughts on moving to Codeberg (or something similar)?

**Comment by syuilo** [comment]
I'm at the point where I haven't read the thread because it's a long one, but I personally don't feel the need to migrate because I have no complaints with GitHub.

**Comment by ThatOneCalculator** [comment]
If you want a TL;DR:

- Github is willing to suspend accounts and inconvenience orgs, repos, and people who have done nothing wrong
- The FSF has declared Github one of the worst places to host code
- **Github's new ToS violates the license of this code** (GPL-3)
- More and more people are moving to Codeberg, and with benefits and free CI for FOSS projects it seems like a relaly good idea right now.

With that said, it's fine if you want to stay on Github, but me and many others think it might not be a good idea.

**Comment by syuilo** [comment]
👀
https://sfconservancy.org/blog/2022/jun/30/give-up-github-launch/

**Comment by ThatOneCalculator** [comment]
Yea, should've linked that too. Github's been bad for a while, this just proves that it's not a good platform to host code on. I seriously hope you consider Codeberg.

**Comment by 4ioskd** [comment]
As far as I know, several fedi softwares have the main repo and also mirror-repo to clone and backup of the main one.

For example:
・Lemmy（https://github.com/LemmyNet/lemmy）
GitHub Gitea Codeberg
・PeerTube（https://github.com/Chocobozzz/PeerTube）
GitHub Framagit( it's based on Gitlab )
・Plume (https://github.com/Plume-org/Plume)
Github Gitea

It may be a good idea to mange a mirror-repo as a backup. and I think Gitea is a good for us. It is fully translated Japanese lang and has a plan to implement with ActivityPub. If its implementation is completed, we can contribute Misskey not only on this repo but also on fedi.

FIY:

WIP: Federated following
https://gitea.com/Ta180m/gitea/pulls/6

**Comment by rinsuki** [comment]
別にgitのミラーの話じゃなくてどっちかというと issues とか pr の話なので…

**Comment by 4ioskd** [comment]
>ThatOneCalculator が凍結されたところ、彼の貴重なIssue/PRやコメントが消え、本リポジトリのディスカッションに著しい不便を強いられることとなった。

最初にaqz氏が書いたように、こういった事が起きたときにミラーのリポジトリに移れば作業が問題なく引き続きできるかぁと思いまして。

**Comment by rinsuki** [comment]
非公開になったissue/prはgitミラーに行こうが(issue/prも頑張ってミラーしない限り)帰ってこないし、このリポジトリにpush権限持たない人のPRのブランチも普通はミラーされないのでgit自体のミラーは今回の件に関してはどうにもならない

**Comment by ThatOneCalculator** [comment]
Honestly, I think in terms of software freedom it'd be better to have all the issues/PRs/etc on Codeberg or Gitea or whatever, and have Github be the read only mirror.

**Comment by tamaina** [comment]
AIに力を入れるならまず翻訳機能とIssueのまとめ機能をつけて欲しい（ただの要望）

**Comment by acid-chicken** [comment]
なんで https://github.com/orgs/community/discussions じゃなくてここに書くの

**Comment by Sayamame-beans** [comment]
triage: Close as staled. If you still think this is needed, please reopen this. 🙏
