### ISSUE TITLE
Was  wrong title and behavior 

### ISSUE THREAD

**Issue by ghost** [syuilo/Misskey#9031]
## 💡 Summary

Email notifications don't work don't work

Sending emails in case of forgotten passwords and for new registrations work!

## 🥰 Expected Behavior

Marking checkbox should enable email notification since Misskey version.

![20220723-1316](https://user-images.githubusercontent.com/58190287/180603053-820f04ab-1cba-4101-9119-e452b838a110.jpg)

## 🤬 Actual Behavior

No emails were sent 

## 📝 Steps to Reproduce

1. Mark related events
2. Wait several days and for related events

Restarting the Misskey service doesn't take effect also.

## 📌 Environment

Misskey version: 12.117.1
Your OS: Debian 11 Bullseye
Your browser: Chrome, Firefox...

**Comment by syuilo** [comment]
This option is intended to indicate the intention to receive notifications from the instance operator (such as scheduled maintenance), but since the functionality for the operator to send emails to users using it has not yet been implemented, nothing will happen if it is enabled for now.
So this is intended and is not a bug. It is not hidden because it may be implemented in the near future and it would be useful to be able to toggle this option in advance.

**Comment by ghost** [comment]
@syuilo  

Then email notifications are something completely different? 
Ok - then they are the ones that don't work.

**Comment by ghost** [comment]
So I changed the title to "Email notifications don't work"

**Comment by ghost** [comment]
I  think it is better to open a new issue and close this one.
