### ISSUE TITLE
While editing a page, I can't add blocks inside section

### ISSUE THREAD

**Issue by tassoman** [syuilo/Misskey#9145]
I've created a new page. Then I added a "section" block after default text block.
Then I've added a text block inside the section but I got an error back:

> **TypeError: t.value.children is undefined**
>     i .........../assets/page-editor.896f074e.js:3
>     1 .........../assets/page-editor.896f074e.js:3
>     Se .........../assets/vue.8d31fef4.js:4
>     xe .........../assets/vue.8d31fef4.js:4
>     n .........../assets/vue.8d31fef4.js:4
> vue.8d31fef4.js:4:1158
>     ql .........../assets/vue.8d31fef4.js:4
>     bt .........../assets/vue.8d31fef4.js:4
>     xe .........../assets/vue.8d31fef4.js:4
>     (Asinc.: promise callback)
>     xe .........../assets/vue.8d31fef4.js:4
>     n .........../assets/vue.8d31fef4.js:4

## Enviroment

- Misskey 12.119.0
- Node.js v16.15.1
- PostgreSQL 12.2
- Redis 4.0.14
- Vue 3.2.39

**Comment by ooozerooo** [comment]
I’m experiencing this as well. I did a little bit of testing and found it’s some changes made between ver. 12.111.1 and ver. 12.116.1 that is causing this problem. Hope it gets solved soon.

**Comment by ooozerooo** [comment]
It's rather confusing because for sections that i created before upgrading to 12.119.0 (but as i mentioned before this bug first appeared between 12.111.1 and 12.116.1, not sure when exactly), i can still add other blocks into it. But for new sections, inserting new blocks doesn't work at all. Dragging a block into a new section also causes the block to disappear.


https://user-images.githubusercontent.com/106132975/200534890-560216b0-8b83-46e2-b651-8a99f7783744.mov


https://user-images.githubusercontent.com/106132975/200537046-bdda561b-ce9d-4dac-8040-63d51fa32352.mov

**Comment by tassoman** [comment]
Looks like drag-n-drop is broken, also. I tried to pull from the hamburger handle but, with no animation nor movement

**Comment by syuilo** [comment]
fixed

**Comment by tassoman** [comment]
Tested and confirmed on 13.0.0-b23
ありがとうございました！
