### ISSUE TITLE
Status bar does not use the parameters in an RSS link

### ISSUE THREAD

**Issue by icecake0107** [syuilo/Misskey#9517]
## 💡 Summary

According to the Hacker News RSS [manual](https://hnrss.github.io/#search-feeds), subscribe to this link 

`https://hnrss.org/show?points=100&link=comments`

Clicking the items should bring me directly to the Hacker News website instead of the submitted article’s URL

## 🥰 Expected Behavior

RSS  <link> should be queried with the parameters in the URL.

## 🤬 Actual Behavior

It ignores the parameters `&parameter` after the `?first` parameter.

## 📝 Steps to Reproduce

1. Open the settings panel
2. Open status bar
3. Use the link `https://hnrss.org/show?points=100&link=comments`
4. Click save
5. Click any item on the status bar
6. It jumps to the article instead of HN comments page. 

## 📌 Environment

Misskey version: [13.0.0-beta.37](https://github.com/misskey-dev/misskey/releases/tag/13.0.0-beta.37)
Your OS: `Ubuntu 22.04.1 LTS`
Your browser: `Firefox-1.8.01`

**Comment by itsjustduc** [comment]
i believe the issue exists because misskey tries to pass the URL itself as a URL parameter, so the URL only lasts until the first `&` in reality. try using URL escape characters (`%26` instead of `&` and `%3F` instead of `?`, tho the latter might not be absolutely necessary).

edit: [URL encoding reference](https://www.w3schools.com/tags/ref_urlencode.asp)
[widget code](https://github.com/misskey-dev/misskey/blob/329830e2c3d1d46de712d1cbe4cf3bac51144dcb/packages/frontend/src/widgets/WidgetRss.vue#L71)
[backend](https://github.com/misskey-dev/misskey/blob/develop/packages/backend/src/server/api/endpoints/fetch-rss.ts)
